import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./style/index.scss";
import '@ant-design/v5-patch-for-react-19'; 

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body>
                <AntdRegistry>
                    {children}
                </AntdRegistry>
            </body>
        </html>
    );
}
